/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function calculateNpcVote(npc: RustPlayer, game: RustGameState, randValues: Array<number>): VoteResult

export interface RustEvidence {
  type: string
  from: string
  target: string
  result: boolean
  visible: boolean
}

export interface RustGameState {
  players: Array<RustPlayer>
  evidence: Array<RustEvidence>
  lovers: Array<string>
  dayCount: number
  isPublicVote: boolean
  chatCounts: Record<string, number>
  voteLogs: Array<RustVoteLog>
}

export interface RustPlayer {
  id: string
  alive: boolean
  role: string
  personality: string
}

export interface RustVoteLog {
  votes: Record<string, string>
}

export interface VoteResult {
  targetId: string
  reasonType: string
}
