-- Retention analytics v2. Existing rows and the v1 daily summary remain valid.
-- New participant identifiers are stable HMAC pseudonyms generated by the bot;
-- participant Discord user IDs, display names, roles, votes, and messages are
-- intentionally not stored here.

alter table public.tomatobot_play_sessions
  add column if not exists chain_id uuid,
  add column if not exists app_version text not null default 'unknown',
  add column if not exists abandon_phase text;

with recursive session_tree as (
  select session.id, session.id as root_id
  from public.tomatobot_play_sessions as session
  where session.source_session_id is null
     or not exists (
       select 1
       from public.tomatobot_play_sessions as parent
       where parent.id = session.source_session_id
     )

  union all

  select child.id, parent.root_id
  from public.tomatobot_play_sessions as child
  join session_tree as parent on parent.id = child.source_session_id
)
update public.tomatobot_play_sessions as session
set chain_id = session_tree.root_id
from session_tree
where session.id = session_tree.id
  and session.chain_id is null;

update public.tomatobot_play_sessions
set chain_id = id
where chain_id is null;

alter table public.tomatobot_play_sessions
  alter column chain_id set default gen_random_uuid(),
  alter column chain_id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tomatobot_play_sessions_app_version_length_check'
      and conrelid = 'public.tomatobot_play_sessions'::regclass
  ) then
    alter table public.tomatobot_play_sessions
      add constraint tomatobot_play_sessions_app_version_length_check
      check (char_length(app_version) between 1 and 100);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'tomatobot_play_sessions_abandon_phase_check'
      and conrelid = 'public.tomatobot_play_sessions'::regclass
  ) then
    alter table public.tomatobot_play_sessions
      add constraint tomatobot_play_sessions_abandon_phase_check
      check (
        abandon_phase is null or abandon_phase in (
          'lobby',
          'role_setup',
          'discussion',
          'voting',
          'night',
          'ended',
          'unknown'
        )
      );
  end if;
end
$$;

create index if not exists tomatobot_play_sessions_chain_id_idx
  on public.tomatobot_play_sessions (chain_id, opened_at);

create index if not exists tomatobot_play_sessions_abandon_phase_idx
  on public.tomatobot_play_sessions (abandon_phase, day_count)
  where status in ('cancelled', 'reset');

create table if not exists public.tomatobot_play_participants (
  session_id uuid not null references public.tomatobot_play_sessions(id) on delete cascade,
  participant_hash text not null check (
    participant_hash ~ '^v1:[0-9a-f]{64}$'
  ),
  is_host boolean not null default false,
  joined_at timestamptz not null default now(),
  primary key (session_id, participant_hash)
);

create index if not exists tomatobot_play_participants_hash_idx
  on public.tomatobot_play_participants (participant_hash, joined_at desc);

alter table public.tomatobot_play_participants enable row level security;
revoke all on table public.tomatobot_play_participants from anon, authenticated;
grant select, insert, update, delete
  on table public.tomatobot_play_participants
  to service_role;

alter table public.tomatobot_match_feedback
  add column if not exists participant_hash text,
  add column if not exists chain_id uuid,
  add column if not exists reason text;

-- v1 stored the Discord ID in user_id. It is no longer needed for counting, so
-- remove the direct identifier while keeping every historical response.
update public.tomatobot_match_feedback
set user_id = 'legacy:' || gen_random_uuid()::text
where participant_hash is null
  and user_id not like 'legacy:%';

update public.tomatobot_match_feedback as feedback
set chain_id = coalesce(session.chain_id, session.id)
from public.tomatobot_play_sessions as session
where session.id = feedback.session_id
  and feedback.chain_id is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tomatobot_match_feedback_user_id_format_check'
      and conrelid = 'public.tomatobot_match_feedback'::regclass
  ) then
    alter table public.tomatobot_match_feedback
      add constraint tomatobot_match_feedback_user_id_format_check
      check (
        user_id like 'legacy:%' or user_id ~ '^v1:[0-9a-f]{64}$'
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'tomatobot_match_feedback_participant_hash_check'
      and conrelid = 'public.tomatobot_match_feedback'::regclass
  ) then
    alter table public.tomatobot_match_feedback
      add constraint tomatobot_match_feedback_participant_hash_check
      check (
        participant_hash is null or
        participant_hash ~ '^v1:[0-9a-f]{64}$'
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'tomatobot_match_feedback_reason_check'
      and conrelid = 'public.tomatobot_match_feedback'::regclass
  ) then
    alter table public.tomatobot_match_feedback
      add constraint tomatobot_match_feedback_reason_check
      check (
        reason is null or reason in (
          'npc', 'tempo', 'controls', 'roles', 'bug', 'other'
        )
      );
  end if;
end
$$;

create unique index if not exists tomatobot_match_feedback_participant_idx
  on public.tomatobot_match_feedback (session_id, participant_hash)
  where participant_hash is not null;

create unique index if not exists tomatobot_match_feedback_chain_participant_idx
  on public.tomatobot_match_feedback (chain_id, participant_hash)
  where chain_id is not null and participant_hash is not null;

create index if not exists tomatobot_match_feedback_reason_idx
  on public.tomatobot_match_feedback (reason, created_at desc)
  where reason is not null;

-- The first rating wins. A later call may only append a comment when it uses
-- the already-locked rating; it can never change the rating or reason.
create or replace function public.tomatobot_submit_match_feedback(
  p_session_id uuid,
  p_participant_hash text,
  p_rating text,
  p_reason text,
  p_comment text
)
returns table (outcome text, locked_rating text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  inserted_count integer;
  session_chain_id uuid;
  existing_rating text;
  existing_comment text;
  normalized_comment text;
begin
  if p_participant_hash is null or
     p_participant_hash !~ '^v1:[0-9a-f]{64}$' then
    raise exception 'invalid participant hash';
  end if;
  if p_rating not in ('again', 'neutral', 'issue') then
    raise exception 'invalid feedback rating';
  end if;
  if p_reason is not null and
     p_reason not in ('npc', 'tempo', 'controls', 'roles', 'bug', 'other') then
    raise exception 'invalid feedback reason';
  end if;

  normalized_comment := nullif(left(btrim(coalesce(p_comment, '')), 1000), '');

  select coalesce(session.chain_id, session.id)
  into session_chain_id
  from public.tomatobot_play_sessions as session
  where session.id = p_session_id;

  if session_chain_id is null then
    raise exception 'play session not found';
  end if;

  insert into public.tomatobot_match_feedback (
    session_id,
    user_id,
    participant_hash,
    chain_id,
    rating,
    reason,
    comment
  ) values (
    p_session_id,
    p_participant_hash,
    p_participant_hash,
    session_chain_id,
    p_rating,
    p_reason,
    normalized_comment
  )
  on conflict (chain_id, participant_hash)
    where chain_id is not null and participant_hash is not null
    do nothing;

  get diagnostics inserted_count = row_count;
  if inserted_count = 1 then
    return query select 'created'::text, p_rating::text;
    return;
  end if;

  select feedback.rating, feedback.comment
  into existing_rating, existing_comment
  from public.tomatobot_match_feedback as feedback
  where feedback.chain_id = session_chain_id
    and feedback.participant_hash = p_participant_hash
  for update;

  if existing_rating is null then
    raise exception 'feedback conflict could not be resolved';
  end if;

  if normalized_comment is not null and existing_rating = p_rating then
    if existing_comment is null then
      update public.tomatobot_match_feedback
      set comment = normalized_comment,
          updated_at = now()
      where chain_id = session_chain_id
        and participant_hash = p_participant_hash;
    elsif existing_comment <> normalized_comment and
          right(existing_comment, char_length(normalized_comment) + 1) <>
            E'\n' || normalized_comment then
      update public.tomatobot_match_feedback
      set comment = left(existing_comment || E'\n' || normalized_comment, 1000),
          updated_at = now()
      where chain_id = session_chain_id
        and participant_hash = p_participant_hash;
    end if;

    return query select 'comment_appended'::text, existing_rating::text;
    return;
  end if;

  return query select 'locked'::text, existing_rating::text;
end;
$$;

revoke execute on function public.tomatobot_submit_match_feedback(
  uuid, text, text, text, text
) from public, anon, authenticated;
grant execute on function public.tomatobot_submit_match_feedback(
  uuid, text, text, text, text
) to service_role;

-- JST-based product metrics. Participant metrics begin when this migration and
-- the matching bot release are deployed; legacy sessions remain in session totals.
create or replace view public.tomatobot_play_daily_summary_v2
with (security_invoker = true)
as
with session_base as (
  select
    session.*,
    (session.opened_at at time zone 'Asia/Tokyo')::date as play_day
  from public.tomatobot_play_sessions as session
),
session_totals as (
  select
    play_day,
    count(*) as lobbies,
    count(*) filter (where started_at is not null) as started,
    count(*) filter (where status = 'completed') as completed,
    count(*) filter (where status in ('cancelled', 'reset')) as abandoned,
    count(*) filter (where rematch_requested_at is not null) as rematches,
    count(distinct chain_id) as chains,
    count(distinct guild_id) as active_guilds,
    count(*) filter (
      where started_at is not null and human_count = 1
    ) as solo_starts,
    count(*) filter (
      where started_at is not null and human_count > 1
    ) as multiplayer_starts,
    count(*) filter (
      where status in ('cancelled', 'reset') and abandon_phase = 'lobby'
    ) as abandoned_lobby,
    count(*) filter (
      where status in ('cancelled', 'reset') and abandon_phase = 'role_setup'
    ) as abandoned_role_setup,
    count(*) filter (
      where status in ('cancelled', 'reset') and abandon_phase = 'discussion'
    ) as abandoned_discussion,
    count(*) filter (
      where status in ('cancelled', 'reset') and abandon_phase = 'voting'
    ) as abandoned_voting,
    count(*) filter (
      where status in ('cancelled', 'reset') and abandon_phase = 'night'
    ) as abandoned_night,
    round(
      avg(duration_seconds) filter (where status = 'completed')
    ) as average_completed_seconds
  from session_base
  group by play_day
),
participant_days as (
  select distinct
    session.play_day,
    participant.participant_hash
  from session_base as session
  join public.tomatobot_play_participants as participant
    on participant.session_id = session.id
  where session.started_at is not null
),
participant_first_day as (
  select participant_hash, min(play_day) as first_day
  from participant_days
  group by participant_hash
),
participant_totals as (
  select
    participant.play_day,
    count(*) as unique_players,
    count(*) filter (
      where first_seen.first_day = participant.play_day
    ) as new_players,
    count(*) filter (
      where first_seen.first_day < participant.play_day
    ) as returning_players
  from participant_days as participant
  join participant_first_day as first_seen
    on first_seen.participant_hash = participant.participant_hash
  group by participant.play_day
),
chain_lengths as (
  select
    chain_id,
    min(play_day) as chain_day,
    count(*) filter (where started_at is not null) as started_matches
  from session_base
  group by chain_id
),
chain_totals as (
  select
    chain_day as play_day,
    count(*) filter (where started_matches > 0) as started_chains,
    round(
      avg(started_matches) filter (where started_matches > 0),
      2
    ) as average_matches_per_chain,
    round(
      100.0 * count(*) filter (where started_matches >= 2) /
      nullif(count(*) filter (where started_matches >= 1), 0),
      1
    ) as first_to_second_match_rate_percent
  from chain_lengths
  group by chain_day
),
feedback_totals as (
  select
    (session.opened_at at time zone 'Asia/Tokyo')::date as play_day,
    count(*) filter (where rating = 'again') as feedback_again,
    count(*) filter (where rating = 'neutral') as feedback_neutral,
    count(*) filter (where rating = 'issue') as feedback_issue,
    count(*) filter (where reason = 'npc') as reason_npc,
    count(*) filter (where reason = 'tempo') as reason_tempo,
    count(*) filter (where reason = 'controls') as reason_controls,
    count(*) filter (where reason = 'roles') as reason_roles,
    count(*) filter (where reason = 'bug') as reason_bug,
    count(*) filter (where reason = 'other') as reason_other
  from public.tomatobot_match_feedback as feedback
  join public.tomatobot_play_sessions as session
    on session.id = feedback.session_id
  group by (session.opened_at at time zone 'Asia/Tokyo')::date
)
select
  session.play_day as day_jst,
  session.lobbies,
  session.started,
  session.completed,
  session.abandoned,
  session.rematches,
  session.chains,
  session.active_guilds,
  coalesce(chain.started_chains, 0) as started_chains,
  session.solo_starts,
  session.multiplayer_starts,
  coalesce(participant.unique_players, 0) as unique_players,
  coalesce(participant.new_players, 0) as new_players,
  coalesce(participant.returning_players, 0) as returning_players,
  round(
    100.0 * session.completed / nullif(session.started, 0),
    1
  ) as completion_rate_percent,
  chain.average_matches_per_chain,
  chain.first_to_second_match_rate_percent,
  session.average_completed_seconds,
  session.abandoned_lobby,
  session.abandoned_role_setup,
  session.abandoned_discussion,
  session.abandoned_voting,
  session.abandoned_night,
  coalesce(feedback.feedback_again, 0) as feedback_again,
  coalesce(feedback.feedback_neutral, 0) as feedback_neutral,
  coalesce(feedback.feedback_issue, 0) as feedback_issue,
  coalesce(feedback.reason_npc, 0) as reason_npc,
  coalesce(feedback.reason_tempo, 0) as reason_tempo,
  coalesce(feedback.reason_controls, 0) as reason_controls,
  coalesce(feedback.reason_roles, 0) as reason_roles,
  coalesce(feedback.reason_bug, 0) as reason_bug,
  coalesce(feedback.reason_other, 0) as reason_other
from session_totals as session
left join participant_totals as participant
  on participant.play_day = session.play_day
left join chain_totals as chain
  on chain.play_day = session.play_day
left join feedback_totals as feedback
  on feedback.play_day = session.play_day;

create or replace view public.tomatobot_player_retention_cohorts
with (security_invoker = true)
as
with participant_days as (
  select distinct
    participant.participant_hash,
    (session.started_at at time zone 'Asia/Tokyo')::date as play_day
  from public.tomatobot_play_participants as participant
  join public.tomatobot_play_sessions as session
    on session.id = participant.session_id
  where session.started_at is not null
),
cohorts as (
  select participant_hash, min(play_day) as cohort_day
  from participant_days
  group by participant_hash
)
select
  cohort.cohort_day as cohort_day_jst,
  count(*) as new_players,
  case
    when (now() at time zone 'Asia/Tokyo')::date > cohort.cohort_day + 1
    then count(*) filter (
      where exists (
        select 1
        from participant_days as played
        where played.participant_hash = cohort.participant_hash
          and played.play_day = cohort.cohort_day + 1
      )
    )
  end as returned_day_1,
  case
    when (now() at time zone 'Asia/Tokyo')::date > cohort.cohort_day + 7
    then count(*) filter (
      where exists (
        select 1
        from participant_days as played
        where played.participant_hash = cohort.participant_hash
          and played.play_day = cohort.cohort_day + 7
      )
    )
  end as returned_day_7,
  case
    when (now() at time zone 'Asia/Tokyo')::date > cohort.cohort_day + 1
    then round(
      100.0 * count(*) filter (
        where exists (
          select 1
          from participant_days as played
          where played.participant_hash = cohort.participant_hash
            and played.play_day = cohort.cohort_day + 1
        )
      ) / nullif(count(*), 0),
      1
    )
  end as retention_day_1_percent,
  case
    when (now() at time zone 'Asia/Tokyo')::date > cohort.cohort_day + 7
    then round(
      100.0 * count(*) filter (
        where exists (
          select 1
          from participant_days as played
          where played.participant_hash = cohort.participant_hash
            and played.play_day = cohort.cohort_day + 7
        )
      ) / nullif(count(*), 0),
      1
    )
  end as retention_day_7_percent
from cohorts as cohort
group by cohort.cohort_day;

revoke all on table public.tomatobot_play_daily_summary_v2
  from anon, authenticated;
revoke all on table public.tomatobot_player_retention_cohorts
  from anon, authenticated;
grant select on table public.tomatobot_play_daily_summary_v2 to service_role;
grant select on table public.tomatobot_player_retention_cohorts to service_role;
